version: "3.7"

services:
  bootstrap:
    restart: always
    build:
      target: prod
      context: .
      dockerfile: Dockerfile
    image: bootstrap:latest    
    environment:
      VIRTUAL_HOST: ${ENJOY_HOST:?Host required}
      LETSENCRYPT_HOST: ${ENJOY_HOST:?Host required}

    networks:
      - docker_default


networks:
  docker_default:
    external: true
    name: docker_default
